# .github/workflows/main.yml
#
on:
  schedule:
    # https://crontab.guru/#*_*/6_*_*_*
    # “At every minute past every 6th hour.”
    - cron: '* */12 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/60bbdb08f10711260e10d3b1
