# .github/workflows/main.yml
#
on:
  schedule:
    # https://crontab.guru/#0_4_*_*_*
    # "at 04:00."
    #
    - cron: '0 4 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/60bbdb08f10711260e10d3b1
